/// Flutter icons KoreaMonkey
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KoreaMonkey
///      fonts:
///       - asset: fonts/KoreaMonkey.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KoreaMonkey {
  KoreaMonkey._();

  static const _kFontFam = 'KoreaMonkey';
  static const String? _kFontPkg = null;

  static const IconData title_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
