DATABASE_NAME=mini_blog
USER=bn3monkey
PASSWORD=`cat password`
PORT=5432

ROOT_DATABASE_NAME=postgres
ROOT_USER=postgres
ROOT_PASSWORD=`cat superuser_password`

PGPASSWORD=$ROOT_PASSWORD psql -h localhost -U $ROOT_USER -d $ROOT_DATABASE_NAME -p $PORT -c "CREATE USER $USER WITH PASSWORD '$PASSWORD'"
PGPASSWORD=$ROOT_PASSWORD psql -h localhost -U $ROOT_USER -d $ROOT_DATABASE_NAME -p $PORT -c "ALTER ROLE $USER WITH CREATEDB REPLICATION"
PGPASSWORD=$ROOT_PASSWORD psql -h localhost -U $ROOT_USER -d $ROOT_DATABASE_NAME -p $PORT -c "CREATE DATABASE $DATABASE_NAME OWNER $USER"
PGPASSWORD=$PASSWORD psql -h localhost -U $USER -d $DATABASE_NAME -p $PORT -a -f mini_blog.sql