/// Flutter icons KoreaMonkey
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KoreaMonkey
///      fonts:
///       - asset: fonts/KoreaMonkey.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KoreaMonkey {
  KoreaMonkey._();

  static const _kFontFam = 'KoreaMonkey';
  static const String? _kFontPkg = null;

  static const IconData korea_monkey = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
